### ISSUE TITLE
still working on this project?

### ISSUE THREAD

**Issue by xiandong79** [s-brez/trading-server#1]
do you have a slack channel?

**Comment by s-brez** [comment]
Definitely still working on this, just been busy with other stuff last few months. 

I'll be giving this project full attention December through June 2020.

No slack channel, though I am on telegram @s_brez.

**Comment by s-brez** [comment]
https://join.slack.com/t/sdbgroup/shared_invite/enQtODQ4ODQ3NDI2Njc3LTRjYWNkMGUwYzgwOWM0NTY1ZWM0NzRjNDNkNTdhYWUwMzQyNjNhZmNmNTFkNjRjYjMyNzkwYzg5YjQ2OGQzOGI
